name: Releases

on: 
  push:
    branches: ['UE5.4']
    paths: ['RELEASE_VERSION']

  workflow_dispatch:
      inputs:
        commitsha:
          description: "Commit SHA for the release (if blank use latest on this branch)"

env:
  commitsha: "${{ github.event.inputs.commitsha || github.sha }}"

jobs:

  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./

    permissions: write-all
    steps:
    - name: "Checkout source code"
      uses: actions/checkout@v3
      with:
        ref: "${{ env.commitsha }}"

    - name: Read the RELEASE_VERSION file
      id: getversion
      run: echo "version=$(cat RELEASE_VERSION)" >> $GITHUB_OUTPUT

    - uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        registry-url: 'https://registry.npmjs.org'

    - name: Install library deps
      working-directory: ./Frontend/library
      run: npm ci

    - name: Build frontend lib
      working-directory: ./Frontend/library
      run: npm run build

    - name: Install ui-library deps
      working-directory: ./Frontend/ui-library
      run: npm ci

    - name: NPM link frontend lib into ui-library
      working-directory: ./Frontend/ui-library
      run: npm link ../library

    - name: Build frontend ui-library
      working-directory: ./Frontend/ui-library
      run: npm run build-all

    - name: Install implementations/typescript deps
      working-directory: ./Frontend/implementations/typescript
      run: npm ci

    - name: NPM link frontend and ui-library into implementations/typescript
      working-directory: ./Frontend/implementations/typescript
      run: npm link ../../library ../../ui-library

    - name: Build implementations/typescript
      working-directory: ./Frontend/implementations/typescript
      run: npm run build-all

    - name: Move all content into output directory for archiving
      run: items=(*) && mkdir PixelStreamingInfrastructure-${{ github.ref_name }}-${{ steps.getversion.outputs.version }} && mv ${items[*]} PixelStreamingInfrastructure-${{ github.ref_name }}-${{ steps.getversion.outputs.version }}/

    - name: Archive Release tar.gz
      uses: thedoctor0/zip-release@0.7.1
      with:
        directory: '.'
        path: 'PixelStreamingInfrastructure-${{ github.ref_name }}-${{ steps.getversion.outputs.version }}'
        type: 'tar'
        filename: '${{ github.ref_name }}-${{ steps.getversion.outputs.version }}.tar.gz'
        exclusions: >-
          .git
          .github
          output
          Common/build
          Common/docs
          Common/node_modules
          Docs
          Extras
          Frontend/Docs
          Frontend/implementations/typescript/node_modules
          Frontend/library/dist
          Frontend/library/node_modules
          Frontend/library/types
          Frontend/ui-library/dist
          Frontend/ui-library/node_modules
          Frontend/ui-library/types
          SFU/Docs
          SFU/node_modules
          Signalling/build
          Signalling/docs
          Signalling/node_modules
          SignallingWebServer/build
          SignallingWebServer/node_modules
          SS_Test

    - name: Archive Release .zip
      uses: thedoctor0/zip-release@0.7.1
      with:
        directory: '.'
        path: 'PixelStreamingInfrastructure-${{ github.ref_name }}-${{ steps.getversion.outputs.version }}'
        type: 'zip'
        filename: '${{ github.ref_name }}-${{ steps.getversion.outputs.version }}.zip'
        exclusions: >-
          */.git/*
          */.github/*
          */node_modules/*
          */output/*
          /*/Common/build/*
          /*/Common/docs/*
          /*/Docs/*
          /*/Extras/*
          /*/Frontend/Docs/*
          /*/Frontend/library/dist/*
          /*/Frontend/library/types/*
          /*/Frontend/ui-library/dist/*
          /*/Frontend/ui-library/types/*
          /*/SFU/Docs/*
          /*/Signalling/build/*
          /*/Signalling/docs/*
          /*/SignallingWebServer/build/*
          /*/SS_Test/*

    - name: "Make the release"
      uses: ncipollo/release-action@v1
      with:
        tag: "${{ github.ref_name }}-${{ steps.getversion.outputs.version }}"
        artifacts: "${{ github.ref_name }}-${{ steps.getversion.outputs.version }}.zip,${{ github.ref_name }}-${{ steps.getversion.outputs.version }}.tar.gz"
        generateReleaseNotes: true
        commit: "${{ env.commitsha }}"
